Version 2.0
Some of the changes:

   *settings.org*
   - Refactored configuration file with heavy usage of use-package
   - Improved installation on new machines
   - Added Languagetool
   - Term with 256 colors!
   - Tons of fixes and improvements
   *dunstrc*
   - Added support to desktop notifications with dunst
   *autojump*
   - Switched to autojump instead of fasd
   *gpg*
   - Two different pinentries for emacs and tty modes
   *hwdb*
   - Extra key bindigs now are with udev
   *zshrc*
   - Improved directory tracking
   *_root*
   - /etc configurations are under version control

diff --git a/scripts/bin/commitorgs b/scripts/bin/commitorgs
--- a/scripts/bin/commitorgs
+++ b/scripts/bin/commitorgs
@@ -1,57 +1,15 @@
 #!/bin/sh
 
-logfile="/tmp/$$.log"
-cd "/home/sbozzolo/documents/orgs/"
-git add * >> $logfile
-git commit -m "$(date +'%Y-%m-%d %H:%M')" >> $logfile
-git push origin master >> $logfile
-# /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola '*Ho committato gli orgs!*'"
-# while read -r line
-# do
-#     /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola $line"
-# done < $logfile
-# /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola 'Commit del giorno"
-rm $logfile
+folders_to_backup=("/home/sbozzolo/documents" "/home/sbozzolo/documents/orgs")
 
-logfile="/tmp/$$.log"
-cd "/home/sbozzolo/documents/unimi/masters/master_thesis/thesis/"
-git add * >> $logfile
-git commit -m "$(date +'%Y-%m-%d %H:%M')" >> $logfile
-git push origin master >> $logfile
-# /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola '*Ho committato gli orgs!*'"
-# while read -r line
-# do
-#     /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola $line"
-# done < $logfile
-# /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola 'Commit del giorno"
-rm $logfile
-
-
-logfile="/tmp/$$.log"
-cd "/home/sbozzolo/documents"
-git add * >> $logfile
-git commit -m "$(date +'%Y-%m-%d %H:%M')" >> $logfile
-git push origin master >> $logfile
-# /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola '*Ho committato gli orgs!*'"
-# while read -r line
-# do
-#     /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola $line"
-# done < $logfile
-# /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola 'Commit del giorno"
-rm $logfile
-
-logfile="/tmp/$$.log"
-cd "/home/sbozzolo/documents/working_papers/2017/rotation_law/"
-git add mnras* >> $logfile
-git add figures >> $logfile
-git add rotation_law.tex >> $logfile
-git add rotation_law.pdf >> $logfile
-git commit -m "$(date +'%Y-%m-%d %H:%M')" >> $logfile
-git push origin master >> $logfile
-# /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola '*Ho committato gli orgs!*'"
-# while read -r line
-# do
-#     /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola $line"
-# done < $logfile
-# /home/sbozzolo/tg/bin/telegram-cli -W -e  "msg Gabriele_Bozzola 'Commit del giorno"
-rm $logfile
+for f in "$folders_to_backup"
+do
+    cd "$f"
+    git add * > /dev/null 2>&1
+    git commit -m "$(date +'%Y-%m-%d %H:%M')" > /dev/null 2>&1
+    git push origin master > /dev/null 2>&1
+    if [ ! $? -eq 0 ]
+    then
+        logger -p 2 "Error in the backup process!"
+    fi
+done
